services:
  consul:
    image: hashicorp/consul:1.15.4
    ports:
      - "8500:8500"
    command: agent -server -bootstrap -ui -client=0.0.0.0

  catalogue:
    build: 
      context: ./catalogue
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./catalogue:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    command: npm run dev
    depends_on:
      - consul

  commande:
    build: 
      context: ./commande
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./commande:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    command: npm run dev
    depends_on:
      - consul
      - catalogue
