version: '3.8'

services:
  commande:
    build: 
      context: ./commande
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./commande:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
